# Generated by Django 3.1.14 on 2022-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_cs',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_de',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_pl',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
